In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("car data.csv")
df.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [3]:
df.shape          
df.columns        
df.info()         
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19237 non-null  int64
 1   Price             19237 non-null  int64
 2   Levy              19237 non-null  object
 3   Manufacturer      19237 non-null  object
 4   Model             19237 non-null  object
 5   Prod. year        19237 non-null  int64
 6   Category          19237 non-null  object
 7   Leather interior  19237 non-null  object
 8   Fuel type         19237 non-null  object
 9   Engine volume     19237 non-null  object
 10  Mileage           19237 non-null  object
 11  Cylinders         19237 non-null  float64
 12  Gear box type     19237 non-null  object
 13  Drive wheels      19237 non-null  object
 14  Doors             19237 non-null  object
 15  Wheel             19237 non-null  object
 16  Color             19237 non-null  object
 17  Airbags           19237 non-null  int64
dtypes: float64(1), int64(4), object(13)
memory usage: 2.6+ MB

                 ID         Price    Prod. year     Cylinders       Airbags
count  1.923700e+04  1.923700e+04  19237.000000  19237.000000  19237.000000
mean   4.557654e+07  1.855593e+04   2010.912824      4.582991      6.582627
std    9.365914e+05  1.905813e+05      5.668673      1.199933      4.320168
min    2.074688e+07  1.000000e+00   1939.000000      1.000000      0.000000
25%    4.569837e+07  5.331000e+03   2009.000000      4.000000      4.000000
50%    4.577231e+07  1.317200e+04   2012.000000      4.000000      6.000000
75%    4.580204e+07  2.207500e+04   2015.000000      4.000000     12.000000
max    4.581665e+07  2.630750e+07   2020.000000     16.000000     16.000000

In [4]:
df.columns = df.columns.str.strip().str.replace(" ", "_")
df.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Model', 'Prod._year',
       'Category', 'Leather_interior', 'Fuel_type', 'Engine_volume', 'Mileage',
       'Cylinders', 'Gear_box_type', 'Drive_wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

In [5]:
df['Price'] = df['Price'].fillna(df['Price'].mean())

In [6]:
df.columns = df.columns.str.strip().str.replace(" ", "_")
df.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Model', 'Prod._year',
       'Category', 'Leather_interior', 'Fuel_type', 'Engine_volume', 'Mileage',
       'Cylinders', 'Gear_box_type', 'Drive_wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

In [7]:
df.isnull().sum()

ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod._year          0
Category            0
Leather_interior    0
Fuel_type           0
Engine_volume       0
Mileage             0
Cylinders           0
Gear_box_type       0
Drive_wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
dtype: int64

In [8]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Price'].fillna(df['Price'].mean(), inplace=True)

C:\Users\azizm\AppData\Local\Temp\ipykernel_10724\2312305649.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(df['Price'].mean(), inplace=True)

In [9]:
df['Mileage'] = df['Mileage'].str.replace(' km', '')
df['Mileage'] = pd.to_numeric(df['Mileage'], errors='coerce')
df['Mileage'].fillna(df['Mileage'].median(), inplace=True)

C:\Users\azizm\AppData\Local\Temp\ipykernel_10724\3605766385.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Mileage'].fillna(df['Mileage'].median(), inplace=True)

In [10]:
df['Engine_volume'] = df['Engine_volume'].str.extract('(\d+\.\d+)')
df['Engine_volume'] = pd.to_numeric(df['Engine_volume'], errors='coerce')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\azizm\AppData\Local\Temp\ipykernel_10724\2551181765.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Engine_volume'] = df['Engine_volume'].str.extract('(\d+\.\d+)')

In [11]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [12]:
df['Car_Age'] = 2026 - df['Prod._year']

In [13]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 18924 entries, 0 to 19236
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18924 non-null  int64
 1   Price             18924 non-null  int64
 2   Levy              18924 non-null  object
 3   Manufacturer      18924 non-null  object
 4   Model             18924 non-null  object
 5   Prod._year        18924 non-null  int64
 6   Category          18924 non-null  object
 7   Leather_interior  18924 non-null  object
 8   Fuel_type         18924 non-null  object
 9   Engine_volume     13947 non-null  float64
 10  Mileage           18924 non-null  int64
 11  Cylinders         18924 non-null  float64
 12  Gear_box_type     18924 non-null  object
 13  Drive_wheels      18924 non-null  object
 14  Doors             18924 non-null  object
 15  Wheel             18924 non-null  object
 16  Color             18924 non-null  object
 17  Airbags           18924 non-null  int64
 18  Car_Age           18924 non-null  int64
dtypes: float64(2), int64(6), object(11)
memory usage: 2.9+ MB

,ID,Price,Prod._year,Engine_volume,Mileage,Cylinders,Airbags,Car_Age
count,1.892400e+04,1.892400e+04,18924.000000,13947.000000,1.892400e+04,18924.000000,18924.000000,18924.000000
mean,4.557538e+07,1.858744e+04,2010.914236,2.333297,1.555373e+06,4.580216,6.568379,15.085764
std,9.375468e+05,1.921356e+05,5.665749,0.930867,4.880221e+07,1.200223,4.322323,5.665749
min,2.074688e+07,1.000000e+00,1939.000000,0.100000,0.000000e+00,1.000000,0.000000,6.000000
25%,4.569501e+07,5.331000e+03,2009.000000,1.600000,7.019575e+04,4.000000,4.000000,11.000000
50%,4.577191e+07,1.317200e+04,2012.000000,2.200000,1.264000e+05,4.000000,6.000000,14.000000
75%,4.580174e+07,2.206300e+04,2015.000000,2.500000,1.891198e+05,4.000000,12.000000,17.000000
max,4.581665e+07,2.630750e+07,2020.000000,7.300000,2.147484e+09,16.000000,16.000000,87.000000

In [14]:
df['Engine_volume'] = df['Engine_volume'].fillna(df['Engine_volume'].median())

In [15]:
# Voir les très grandes valeurs
df[df['Mileage'] > 1000000].head()

,ID,Price,Levy,Manufacturer,Model,Prod._year,Category,Leather_interior,Fuel_type,Engine_volume,Mileage,Cylinders,Gear_box_type,Drive_wheels,Doors,Wheel,Color,Airbags,Car_Age
144,45759786,4300,-,MERCEDES-BENZ,208,1985,Universal,No,Diesel,2.5,1111111,4.0,Manual,Rear,04-May,Left wheel,Black,1,41
493,45781924,15994,777,TOYOTA,Camry,2014,Sedan,No,Petrol,2.5,1440000,4.0,Automatic,Front,04-May,Left wheel,Silver,0,12
985,45807165,2700,-,OPEL,Vectra,1997,Sedan,No,CNG,1.6,777777777,4.0,Automatic,Front,04-May,Left wheel,Beige,2,29
1146,44615609,13485,-,BMW,525,2003,Sedan,Yes,Petrol,2.5,7777787,6.0,Manual,Rear,04-May,Left wheel,Silver,10,23
1404,45814878,9095,-,BMW,328,2002,Sedan,No,Petrol,2.8,55556665,6.0,Manual,Rear,04-May,Left wheel,Silver,6,24

In [16]:
df = df[df['Mileage'] < 1000000]

In [17]:
q_low = df['Price'].quantile(0.01)
q_high = df['Price'].quantile(0.99)

df = df[(df['Price'] > q_low) & (df['Price'] < q_high)]

In [18]:
df['Levy'] = df['Levy'].replace('-', np.nan)
df['Levy'] = pd.to_numeric(df['Levy'], errors='coerce')
df['Levy'] = df['Levy'].fillna(df['Levy'].median())

In [19]:
df['Doors'].unique()

array(['04-May', '02-Mar', '>5'], dtype=object)

In [20]:
df['Doors'].dtype

dtype('O')

In [21]:
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18464 entries, 0 to 19236
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18464 non-null  int64
 1   Price             18464 non-null  int64
 2   Levy              18464 non-null  float64
 3   Manufacturer      18464 non-null  object
 4   Model             18464 non-null  object
 5   Prod._year        18464 non-null  int64
 6   Category          18464 non-null  object
 7   Leather_interior  18464 non-null  object
 8   Fuel_type         18464 non-null  object
 9   Engine_volume     18464 non-null  float64
 10  Mileage           18464 non-null  int64
 11  Cylinders         18464 non-null  float64
 12  Gear_box_type     18464 non-null  object
 13  Drive_wheels      18464 non-null  object
 14  Doors             18464 non-null  object
 15  Wheel             18464 non-null  object
 16  Color             18464 non-null  object
 17  Airbags           18464 non-null  int64
 18  Car_Age           18464 non-null  int64
dtypes: float64(3), int64(6), object(10)
memory usage: 2.8+ MB

In [22]:
df.describe()

,ID,Price,Levy,Prod._year,Engine_volume,Mileage,Cylinders,Airbags,Car_Age
count,1.846400e+04,18464.000000,18464.000000,18464.000000,18464.000000,18464.000000,18464.000000,18464.000000,18464.000000
mean,4.558722e+07,16304.833351,867.405817,2010.944649,2.297265,141205.367688,4.570516,6.573007,15.055351
std,8.955997e+05,14701.154152,392.354862,5.599544,0.791919,102620.527240,1.185091,4.322392,5.599544
min,2.074688e+07,47.000000,87.000000,1939.000000,0.100000,0.000000,1.000000,0.000000,6.000000
25%,4.569980e+07,5500.000000,707.000000,2009.000000,1.800000,71193.250000,4.000000,4.000000,12.000000
50%,4.577207e+07,13172.000000,781.000000,2012.000000,2.200000,127000.000000,4.000000,6.000000,14.000000
75%,4.580181e+07,21953.000000,917.000000,2014.000000,2.500000,189000.000000,4.000000,12.000000,17.000000
max,4.581665e+07,83891.000000,11714.000000,2020.000000,7.300000,999999.000000,16.000000,16.000000,87.000000

In [23]:
df.to_csv("cleaned_dataset.csv", index=False)

In [24]:
import os
print(os.getcwd())

d:\USER\Desktop\Study\ING4DS-B\ML\tache 1